language: java
sudo: false

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.m2/"

install: true

before_script:
  # copy Maven settings
  - cp .travis.settings.xml "${HOME}/.m2/settings.xml"

before_deploy:
  # decrypt ReTest secret key
  - openssl aes-256-cbc -K $encrypted_58a7d4f10478_key -iv $encrypted_58a7d4f10478_iv
      -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
  # import decrypted ReTest secret key
  - gpg --fast-import retest-gmbh-gpg.asc
  # package JARs for release providers
  - mvn package -DskipTests

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/recheck-*.jar"
  skip_cleanup: true
  on:
    tags: true
    branch: master

after_deploy:
  - mvn deploy -DskipTests
